"use client";

import type { Metadata } from "next";
import "./globals.css";
import Image from "next/image";
import Twitter from "~icons/fe/twitter";
import Github from "~icons/fe/github-alt";
import Youtube from "~icons/fe/youtube";
import { LinkButton } from "@/components/LinkButton";
import { NavButton } from "@/components/NavButton";
import React, { FC } from "react";
import melodiesdev from "@/assets/melodiesdev.svg";
import line from "@/assets/Line.svg";
import clouds from "@/assets/clouds.svg";
import star from "@/assets/stars.svg";
import "@fontsource/nunito";
import { AnimatePresence, motion } from "framer-motion";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app"
// };

type RootLayoutProps = {
  children: React.ReactNode;
};

const BentLine: FC = () => (
  <div className="dark:invert">
    <Image src={line} alt="line" />
  </div>
);

const Header: FC = () => (
  <div className="relative mx-auto flex w-full max-w-5xl pt-6">
    <div className="absolute -bottom-5 mx-auto">
      <BentLine />
    </div>
    <div className="flex w-full justify-between px-8">
      <div className="flex flex-1 items-center justify-start gap-3 pt-3 font-black text-black dark:invert">
        <NavButton href="/" text="Home" />
        <NavButton href="/artwork" text="Artwork" />
        <NavButton href="/blog" text="Blog" />
      </div>
      <div className="flex items-center justify-center pb-2">
        <Image
          className="invert dark:filter-none"
          src={melodiesdev}
          alt="MelodiesDev"
          width="132"
          height="132"
        />
      </div>
      <div className="flex flex-1 items-center justify-end gap-6 fill-white pt-3 dark:fill-black">
        <LinkButton href="https://twitter.com/melodiesdev">
          <Twitter />
        </LinkButton>
        <LinkButton href="https://github.com/melodiesdev">
          <Github />
        </LinkButton>
        <LinkButton href="https://youtube.com/@MelodiesDevelopment">
          <Youtube />
        </LinkButton>
      </div>
    </div>
  </div>
);

const Footer: FC = () => (
  <div className="flex w-full flex-row justify-between bg-gradient-to-b from-transparent to-pink-100 p-4 font-normal text-black">
    <div>
      <span>Copyright © Melodies Development 2023</span>
    </div>
    <NavButton href="/contact" text="Contact Me" />
  </div>
);

const RootLayout: FC<RootLayoutProps> = ({ children }) => (
  <AnimatePresence mode="wait" initial={false}>
    <html lang="en">
      <body>
        <section className="flex min-h-screen flex-col items-center bg-gradient-to-b from-[#02364A] via-[#39C4F9] to-white dark:bg-gradient-to-b dark:from-[#BBA5FF] dark:via-blue-400 dark:to-white">
          <div className="flex w-full flex-grow flex-col">
            <div className="relative w-full">
              <Image
                src={star}
                alt="stars"
                className="absolute -top-8 left-0 right-0"
                layout="responsive"
              />
              <Image
                className="absolute left-0 right-0 top-0 -z-0 opacity-50"
                src={clouds}
                alt="cloudsandstars"
                layout="responsive"
              />
            </div>
            <Header />
            <div className="z-20 flex-grow">{children}</div>
          </div>
          <Footer />
        </section>
      </body>
    </html>
  </AnimatePresence>
);

export default RootLayout;
