import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import "./globals.css";
import Image from "next/image";
import Twitter from "~icons/fe/twitter";
import Github from "~icons/fe/github-alt";
import Youtube from "~icons/fe/youtube";
import React from "react";
import melodiesdev from "@/assets/melodiesdev.svg";

const nunito = Nunito({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={nunito.className}>
        <section>
          <header className="text-md mx-auto flex w-full max-w-3xl rounded-xl border-b border-white pb-2 pt-6">
            <div className="flex w-full justify-between">
              <div className="flex flex-1 items-center justify-start gap-6 pt-3">
                <h1>Home</h1>
                <h1>Artwork</h1>
                <h1>Blog</h1>
              </div>
              <div className="flex items-center justify-center">
                <Image
                  className="invert dark:filter-none"
                  src={melodiesdev}
                  alt="MelodiesDev"
                  width="132"
                  height="132"
                />
              </div>
              <div className="flex flex-1 items-center justify-end gap-6 pt-3">
                <Twitter />
                <Github />
                <Youtube />
              </div>
            </div>
          </header>
          {children}
        </section>
      </body>
    </html>
  );
}
