import type { Metadata } from "next";
import "./globals.css";
import Image from "next/image";
import Twitter from "~icons/fe/twitter";
import Github from "~icons/fe/github-alt";
import Youtube from "~icons/fe/youtube";
import { LinkButton } from "@/components/LinkButton";
import { NavButton } from "@/components/NavButton";
import React, { FC } from "react";
import melodiesdev from "@/assets/melodiesdev.svg";
import "@fontsource/nunito";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

type RootLayoutProps = {
  children: React.ReactNode;
};

const Header: FC = () => (
  <div className="text-md mx-auto flex w-full max-w-3xl rounded-xl border-b border-black pt-6 dark:border-white">
    <div className="flex w-full justify-between px-8">
      <div className="flex flex-1 items-center justify-start gap-6 pt-3 font-bold text-black dark:invert">
        <NavButton href="/" text="Home" />
        <NavButton href="/artwork" text="Artwork" />
        <NavButton href="/blog" text="Blog" />
      </div>
      <div className="flex items-center justify-center pb-2">
        <Image
          className="invert dark:filter-none"
          src={melodiesdev}
          alt="MelodiesDev"
          width="132"
          height="132"
        />
      </div>
      <div className="flex flex-1 items-center justify-end gap-6 fill-white pt-3 dark:fill-black">
        <LinkButton href="https://twitter.com/melodiesdev">
          <Twitter />
        </LinkButton>
        <LinkButton href="https://github.com/melodiesdev">
          <Github />
        </LinkButton>
        <LinkButton href="https://youtube.com/@MelodiesDevelopment">
          <Youtube />
        </LinkButton>
      </div>
    </div>
  </div>
);

const Footer: FC = () => (
  <div className="to-grey-50 flex w-full flex-row justify-between bg-gradient-to-b from-transparent to-gray-500/30 p-4 font-normal text-black dark:bg-gradient-to-b dark:from-transparent dark:to-gray-800 dark:text-white">
    <div>
      <span>Copyright Me :)</span>
    </div>
    <div>
      <span>Contact Me</span>
    </div>
  </div>
);

const RootLayout: FC<RootLayoutProps> = ({ children }) => (
  <html lang="en">
    <body>
      <section className="flex min-h-screen flex-col items-center bg-gradient-to-br from-[#472E94] via-[#4E33A4] to-[#3C277D] dark:bg-gradient-to-br dark:from-[#221647] dark:via-[#281A54] dark:to-[#160E2E]">
        <div className="flex w-full flex-grow flex-col">
          <Header />
          <div className="flex-grow">{children}</div>
        </div>
        <Footer />
      </section>
    </body>
  </html>
);

export default RootLayout;
